[workspace]
members = [
    "bin/cli",

    "lib",
]

[workspace.dependencies]
hemtt-pbo = { git = "https://github.com/brettmayson/hemtt" }
rayon = "1.10.0"
serde = { version = "1.0.205", features = ["derive"] }
tokio = { version = "1.39.2", features = ["full"] }
